export const APP_NAME = "SISYA Analytics";

export const ROUTES = {
	LOGIN: "/login",
	ADMIN_DASHBOARD: "/admin",
	SUBADMIN_DASHBOARD: "/subadmin",
	ATTENDANCE: "/attendance",
	ADMIN_AI_DOUBT_DETAIL: "/admin/ai/doubt-detail",
	ADMIN_AI_REVIEW: "/admin/ai/review",
	ADMIN_DOUBTS: "/admin/doubts",
	USERS: "/admin/users",
	SETTINGS: "/settings",
	STUDENT_REPORT: "/admin/student-report",
	MENTOR_REPORT: "/admin/mentor-report",
	COURSE_REPORT: "/admin/course-report",
	SUBADMIN_MANAGEMENT: "/admin/subadmin-management",
} as const;

export const API_BASE_URL = "https://staging.sisyaclass.net";

export const API_ENDPOINTS = {
	ADMIN_LOGIN: "/rkadmin/login",
	SUBADMIN_LOGIN: "/rkadmin/subadmin_login",
	GET_COURSES_BY_GRADE: "/rkadmin/get_course_by_grade",
	GET_COMPLETED_SESSIONS: "/rkadmin/get_completed_session",
	GET_SESSION_ATTENDANCE: "/rkadmin/get_session_attendance",
	CREATE_ANNOUNCEMENT: "/rkadmin/create_announcement",
	MARK_AS_SISYA_EMP: "/rkadmin/mark_as_sisya_emp",
	GET_STUDENTS_BY_COURSE: "/rkadmin/get_students_by_course",
	GET_PERFORMANCE_SUMMARY: "/rkadmin/performance/summary",
	GET_PERFORMANCE_ATTENDANCE: "/rkadmin/performance/attendance",
	GET_PERFORMANCE_QUIZZES: "/rkadmin/performance/quizzes",
	GET_PERFORMANCE_TESTS: "/rkadmin/performance/tests",
	GET_PERFORMANCE_HOMEWORK: "/rkadmin/performance/homework",
	GET_PERFORMANCE_COINS: "/rkadmin/performance/coins",
	GET_PERFORMANCE_REVIEWS: "/rkadmin/performance/reviews",
	GET_ACTIVE_MENTORS: "/rkadmin/get_active_mentors",
	GET_MENTOR_PERFORMANCE_SUMMARY: "/rkadmin/performance/mentor/summary",
	GET_MENTOR_PERFORMANCE_REVIEWS: "/rkadmin/performance/mentor/reviews",
	GET_MENTOR_PERFORMANCE_DOUBTS: "/rkadmin/performance/mentor/doubts",
	GET_SESSIONS_BY_MENTOR: "/rkadmin/get_sessions_by_mentor",
	GET_PRESENT_STUDENTS: "/rkadmin/get_present_students",
	GET_SESSION_REVIEWS: "/rkadmin/get_session_reviews",
	GET_MENTOR_REWARD_TRANSACTIONS: "/rkadmin/get_mentor_reward_transactions",
	ALLOCATE_REWARD_BUDGET: "/rkadmin/sisyacoin/reward-budgets/allocate",
	GET_COURSE_PERFORMANCE_SUMMARY: "/rkadmin/performance/course/summary",
	GET_COURSE_PERFORMANCE_SESSIONS: "/rkadmin/performance/course/sessions",
	GET_COURSE_PERFORMANCE_HOMEWORK: "/rkadmin/performance/course/homework",
	GET_COURSE_PERFORMANCE_REVIEWS: "/rkadmin/performance/course/reviews",
	GET_COURSE_PERFORMANCE_TESTS: "/rkadmin/performance/course/tests",
	GET_ALL_SUBADMINS: "/rkadmin/get_all_subadmin",
	UPDATE_SUBADMIN: "/rkadmin/update_subadmin",
	// New Dashboard Specific APIs
	DASHBOARD_OVERVIEW: "/rkadmin/dashboard/overview",
	DASHBOARD_TRENDS_ENROLLMENT: "/rkadmin/dashboard/trends/enrollment",
	DASHBOARD_TRENDS_SESSIONS: "/rkadmin/dashboard/trends/sessions",
	DASHBOARD_PERFORMANCE_COURSES: "/rkadmin/dashboard/performance/courses",
	DASHBOARD_ASSESSMENT_COMPLETION: "/rkadmin/dashboard/assessment/completion",
	DASHBOARD_PERFORMANCE_MENTORS: "/rkadmin/dashboard/performance/mentors",
	DASHBOARD_TRENDS_DOUBTS: "/rkadmin/dashboard/trends/doubts",
	DASHBOARD_RATINGS_DISTRIBUTION: "/rkadmin/dashboard/ratings/distribution",
	DASHBOARD_ACTIVITY_RECENT: "/rkadmin/dashboard/activity/recent",
} as const;

export const GRADES = Array.from({ length: 12 }, (_, i) => (i + 1).toString());
